<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.10.18">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Solara Digital Bank - Independent Risk Assessment">
<meta name="dcterms.date" content="2026-08-15">

<title>Compass: Architecture &amp; Business Case Analysis</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: 1.5em;}
div.column{flex: auto;}
@media screen {
div.columns{gap: min(4vw, 1.5em);}
div.column{overflow-x: auto;}
}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="ARCHITECTURE_files/libs/clipboard/clipboard.min.js"></script>
<script src="ARCHITECTURE_files/libs/quarto-html/quarto.js" type="module"></script>
<script src="ARCHITECTURE_files/libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="ARCHITECTURE_files/libs/quarto-html/popper.min.js"></script>
<script src="ARCHITECTURE_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="ARCHITECTURE_files/libs/quarto-html/anchor.min.js"></script>
<link href="ARCHITECTURE_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="ARCHITECTURE_files/libs/quarto-html/quarto-syntax-highlighting-64a204ab8560d761af7679ceaba22944.css" rel="stylesheet" class="quarto-color-scheme" id="quarto-text-highlighting-styles">
<link href="ARCHITECTURE_files/libs/quarto-html/quarto-syntax-highlighting-dark-b85bc7c33db8c58e0ec93c3465666fed.css" rel="stylesheet" class="quarto-color-scheme quarto-color-alternate" id="quarto-text-highlighting-styles">
<link href="ARCHITECTURE_files/libs/quarto-html/quarto-syntax-highlighting-64a204ab8560d761af7679ceaba22944.css" rel="stylesheet" class="quarto-color-scheme-extra" id="quarto-text-highlighting-styles">
<script src="ARCHITECTURE_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="ARCHITECTURE_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="ARCHITECTURE_files/libs/bootstrap/bootstrap-c2e55264ed47ce3b2e0326a2269f9400.min.css" rel="stylesheet" append-hash="true" class="quarto-color-scheme" id="quarto-bootstrap" data-mode="light">
<link href="ARCHITECTURE_files/libs/bootstrap/bootstrap-dark-23152cf98fc7f0f9fbf5711f0be182d2.min.css" rel="stylesheet" append-hash="true" class="quarto-color-scheme quarto-color-alternate" id="quarto-bootstrap" data-mode="dark">
<link href="ARCHITECTURE_files/libs/bootstrap/bootstrap-c2e55264ed47ce3b2e0326a2269f9400.min.css" rel="stylesheet" append-hash="true" class="quarto-color-scheme-extra" id="quarto-bootstrap" data-mode="light">
<meta name="mermaid-theme" content="neutral">
<script src="ARCHITECTURE_files/libs/quarto-diagram/mermaid.min.js"></script>
<script src="ARCHITECTURE_files/libs/quarto-diagram/mermaid-init.js"></script>
<link href="ARCHITECTURE_files/libs/quarto-diagram/mermaid.css" rel="stylesheet">

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script defer="" src="https://cdn.jsdelivr.net/npm/mathjax@4/tex-chtml.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN" && texText && texText.data) {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

</head>

<body class="quarto-light"><script id="quarto-html-before-body" type="application/javascript">
    const toggleBodyColorMode = (bsSheetEl) => {
      const mode = bsSheetEl.getAttribute("data-mode");
      const bodyEl = window.document.querySelector("body");
      if (mode === "dark") {
        bodyEl.classList.add("quarto-dark");
        bodyEl.classList.remove("quarto-light");
      } else {
        bodyEl.classList.add("quarto-light");
        bodyEl.classList.remove("quarto-dark");
      }
    }
    const toggleBodyColorPrimary = () => {
      const bsSheetEl = window.document.querySelector("link#quarto-bootstrap:not([rel=disabled-stylesheet])");
      if (bsSheetEl) {
        toggleBodyColorMode(bsSheetEl);
      }
    }
    const setColorSchemeToggle = (alternate) => {
      const toggles = window.document.querySelectorAll('.quarto-color-scheme-toggle');
      for (let i=0; i < toggles.length; i++) {
        const toggle = toggles[i];
        if (toggle) {
          if (alternate) {
            toggle.classList.add("alternate");
          } else {
            toggle.classList.remove("alternate");
          }
        }
      }
    };
    const toggleColorMode = (alternate) => {
      // Switch the stylesheets
      const primaryStylesheets = window.document.querySelectorAll('link.quarto-color-scheme:not(.quarto-color-alternate)');
      const alternateStylesheets = window.document.querySelectorAll('link.quarto-color-scheme.quarto-color-alternate');
      manageTransitions('#quarto-margin-sidebar .nav-link', false);
      if (alternate) {
        // note: dark is layered on light, we don't disable primary!
        enableStylesheet(alternateStylesheets);
        for (const sheetNode of alternateStylesheets) {
          if (sheetNode.id === "quarto-bootstrap") {
            toggleBodyColorMode(sheetNode);
          }
        }
      } else {
        disableStylesheet(alternateStylesheets);
        enableStylesheet(primaryStylesheets)
        toggleBodyColorPrimary();
      }
      manageTransitions('#quarto-margin-sidebar .nav-link', true);
      // Switch the toggles
      setColorSchemeToggle(alternate)
      // Hack to workaround the fact that safari doesn't
      // properly recolor the scrollbar when toggling (#1455)
      if (navigator.userAgent.indexOf('Safari') > 0 && navigator.userAgent.indexOf('Chrome') == -1) {
        manageTransitions("body", false);
        window.scrollTo(0, 1);
        setTimeout(() => {
          window.scrollTo(0, 0);
          manageTransitions("body", true);
        }, 40);
      }
    }
    const disableStylesheet = (stylesheets) => {
      for (let i=0; i < stylesheets.length; i++) {
        const stylesheet = stylesheets[i];
        stylesheet.rel = 'disabled-stylesheet';
      }
    }
    const enableStylesheet = (stylesheets) => {
      for (let i=0; i < stylesheets.length; i++) {
        const stylesheet = stylesheets[i];
        if(stylesheet.rel !== 'stylesheet') { // for Chrome, which will still FOUC without this check
          stylesheet.rel = 'stylesheet';
        }
      }
    }
    const manageTransitions = (selector, allowTransitions) => {
      const els = window.document.querySelectorAll(selector);
      for (let i=0; i < els.length; i++) {
        const el = els[i];
        if (allowTransitions) {
          el.classList.remove('notransition');
        } else {
          el.classList.add('notransition');
        }
      }
    }
    const isFileUrl = () => {
      return window.location.protocol === 'file:';
    }
    const hasAlternateSentinel = () => {
      let styleSentinel = getColorSchemeSentinel();
      if (styleSentinel !== null) {
        return styleSentinel === "alternate";
      } else {
        return false;
      }
    }
    const setStyleSentinel = (alternate) => {
      const value = alternate ? "alternate" : "default";
      if (!isFileUrl()) {
        window.localStorage.setItem("quarto-color-scheme", value);
      } else {
        localAlternateSentinel = value;
      }
    }
    const getColorSchemeSentinel = () => {
      if (!isFileUrl()) {
        const storageValue = window.localStorage.getItem("quarto-color-scheme");
        return storageValue != null ? storageValue : localAlternateSentinel;
      } else {
        return localAlternateSentinel;
      }
    }
    const toggleGiscusIfUsed = (isAlternate, darkModeDefault) => {
      const baseTheme = document.querySelector('#giscus-base-theme')?.value ?? 'light';
      const alternateTheme = document.querySelector('#giscus-alt-theme')?.value ?? 'dark';
      let newTheme = '';
      if(authorPrefersDark) {
        newTheme = isAlternate ? baseTheme : alternateTheme;
      } else {
        newTheme = isAlternate ? alternateTheme : baseTheme;
      }
      const changeGiscusTheme = () => {
        // From: https://github.com/giscus/giscus/issues/336
        const sendMessage = (message) => {
          const iframe = document.querySelector('iframe.giscus-frame');
          if (!iframe) return;
          iframe.contentWindow.postMessage({ giscus: message }, 'https://giscus.app');
        }
        sendMessage({
          setConfig: {
            theme: newTheme
          }
        });
      }
      const isGiscussLoaded = window.document.querySelector('iframe.giscus-frame') !== null;
      if (isGiscussLoaded) {
        changeGiscusTheme();
      }
    };
    const authorPrefersDark = false;
    const darkModeDefault = authorPrefersDark;
      document.querySelector('link#quarto-text-highlighting-styles.quarto-color-scheme-extra').rel = 'disabled-stylesheet';
      document.querySelector('link#quarto-bootstrap.quarto-color-scheme-extra').rel = 'disabled-stylesheet';
    let localAlternateSentinel = darkModeDefault ? 'alternate' : 'default';
    // Dark / light mode switch
    window.quartoToggleColorScheme = () => {
      // Read the current dark / light value
      let toAlternate = !hasAlternateSentinel();
      toggleColorMode(toAlternate);
      setStyleSentinel(toAlternate);
      toggleGiscusIfUsed(toAlternate, darkModeDefault);
      window.dispatchEvent(new Event('resize'));
    };
    // Switch to dark mode if need be
    if (hasAlternateSentinel()) {
      toggleColorMode(true);
    } else {
      toggleColorMode(false);
    }
  </script>

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">
<div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
  <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#executive-summary" id="toc-executive-summary" class="nav-link active" data-scroll-target="#executive-summary">Executive Summary</a></li>
  <li><a href="#system-overview" id="toc-system-overview" class="nav-link" data-scroll-target="#system-overview"><span class="header-section-number">1</span> System Overview</a></li>
  <li><a href="#component-architecture" id="toc-component-architecture" class="nav-link" data-scroll-target="#component-architecture"><span class="header-section-number">2</span> Component Architecture</a></li>
  <li><a href="#data-flow-batch-path" id="toc-data-flow-batch-path" class="nav-link" data-scroll-target="#data-flow-batch-path"><span class="header-section-number">3</span> Data Flow — Batch Path</a></li>
  <li><a href="#data-flow-streaming-path" id="toc-data-flow-streaming-path" class="nav-link" data-scroll-target="#data-flow-streaming-path"><span class="header-section-number">4</span> Data Flow — Streaming Path</a></li>
  <li><a href="#database-schema-er-diagram" id="toc-database-schema-er-diagram" class="nav-link" data-scroll-target="#database-schema-er-diagram"><span class="header-section-number">5</span> Database Schema (ER Diagram)</a>
  <ul class="collapse">
  <li><a href="#schema-storage-comparison" id="toc-schema-storage-comparison" class="nav-link" data-scroll-target="#schema-storage-comparison"><span class="header-section-number">5.1</span> Schema &amp; Storage Comparison</a></li>
  </ul></li>
  <li><a href="#uml-class-module-diagram" id="toc-uml-class-module-diagram" class="nav-link" data-scroll-target="#uml-class-module-diagram"><span class="header-section-number">6</span> UML Class &amp; Module Diagram</a></li>
  <li><a href="#execution-sequence-end-to-end" id="toc-execution-sequence-end-to-end" class="nav-link" data-scroll-target="#execution-sequence-end-to-end"><span class="header-section-number">7</span> Execution Sequence — End-to-End</a></li>
  <li><a href="#the-core-risk-trainingserving-skew" id="toc-the-core-risk-trainingserving-skew" class="nav-link" data-scroll-target="#the-core-risk-trainingserving-skew"><span class="header-section-number">8</span> The Core Risk: Training/Serving Skew</a>
  <ul class="collapse">
  <li><a href="#quantifying-the-skew-empirical-validation" id="toc-quantifying-the-skew-empirical-validation" class="nav-link" data-scroll-target="#quantifying-the-skew-empirical-validation"><span class="header-section-number">8.1</span> Quantifying the Skew (Empirical Validation)</a>
  <ul class="collapse">
  <li><a href="#mathematical-divergence-exact-mean-vs.-ewma" id="toc-mathematical-divergence-exact-mean-vs.-ewma" class="nav-link" data-scroll-target="#mathematical-divergence-exact-mean-vs.-ewma"><span class="header-section-number">8.1.1</span> Mathematical Divergence: Exact Mean vs.&nbsp;EWMA</a></li>
  </ul></li>
  </ul></li>
  <li><a href="#risk-mapping-business-case-incidents" id="toc-risk-mapping-business-case-incidents" class="nav-link" data-scroll-target="#risk-mapping-business-case-incidents"><span class="header-section-number">9</span> Risk Mapping &amp; Business Case Incidents</a>
  <ul class="collapse">
  <li><a href="#incident-analysis" id="toc-incident-analysis" class="nav-link" data-scroll-target="#incident-analysis"><span class="header-section-number">9.1</span> Incident Analysis</a></li>
  <li><a href="#risk-assessment-heat-map" id="toc-risk-assessment-heat-map" class="nav-link" data-scroll-target="#risk-assessment-heat-map"><span class="header-section-number">9.2</span> Risk Assessment Heat Map</a></li>
  </ul></li>
  <li><a href="#proposed-solution-architecture" id="toc-proposed-solution-architecture" class="nav-link" data-scroll-target="#proposed-solution-architecture"><span class="header-section-number">10</span> Proposed Solution Architecture</a>
  <ul class="collapse">
  <li><a href="#before-vs.-after-controls" id="toc-before-vs.-after-controls" class="nav-link" data-scroll-target="#before-vs.-after-controls"><span class="header-section-number">10.1</span> Before vs.&nbsp;After Controls</a></li>
  </ul></li>
  <li><a href="#appendix-execution-commands" id="toc-appendix-execution-commands" class="nav-link" data-scroll-target="#appendix-execution-commands"><span class="header-section-number">11</span> Appendix: Execution Commands</a></li>
  </ul>
</nav>
</div>
<main class="content" id="quarto-document-content">


<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Compass: Architecture &amp; Business Case Analysis</h1>
<p class="subtitle lead">Model Risk Specialist — ML/AI Data &amp; Infrastructure Risks (IC5)</p>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Solara Digital Bank - Independent Risk Assessment </p>
          </div>
  </div>
    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">August 15, 2026</p>
    </div>
  </div>
  
    
  </div>
  


</header>


<section id="executive-summary" class="level1 unnumbered">
<h1 class="unnumbered">Executive Summary</h1>
<p>This document contains a comprehensive, hands-on validation and independent risk assessment of <strong>Compass</strong>, Solara Digital Bank’s internal feature store and serving pipeline.</p>
<p>As the Model Risk function’s second line of defense, this assessment identifies critical structural, algorithmic, and governance risks within the system prior to the proposed expansions: 1. Powering the new <strong>instant credit-line top-up</strong> feature with no human oversight. 2. Lightening the current <strong>change-review process</strong> for feature transformation code.</p>
<hr>
</section>
<section id="system-overview" class="level1" data-number="1">
<h1 data-number="1"><span class="header-section-number">1</span> System Overview</h1>
<p>The flowchart below illustrates the end-to-end architecture of Compass, highlighting the separation between the Batch and Streaming paths.</p>
<div class="cell" data-layout-align="default">
<div class="cell-output-display">
<div>
<p></p><figure class="figure"><p></p>
<div>
<pre class="mermaid mermaid-js">graph TB
    subgraph Inputs["📥 Inputs"]
        TXN["transactions.csv&lt;br/&gt;(32,929 rows · 300 customers)"]
    end

    subgraph Pipelines["⚙️ Feature Pipelines"]
        BATCH["Batch Pipeline&lt;br/&gt;(nightly · full recompute)"]
        STREAM["Streaming Pipeline&lt;br/&gt;(incremental · event-by-event)"]
    end

    subgraph Stores["🗄️ Feature Stores (SQLite)"]
        OFFLINE["Offline Store&lt;br/&gt;offline_store.db&lt;br/&gt;(point-in-time keyed)"]
        ONLINE["Online Store&lt;br/&gt;online_store.db&lt;br/&gt;(latest value per customer)"]
    end

    subgraph API["🔌 Serving API"]
        FAPI["feature_api.py&lt;br/&gt;get_offline_features()&lt;br/&gt;get_online_features()"]
    end

    subgraph Consumers["🏦 Downstream Consumers"]
        UNDER["Underwriting Model&lt;br/&gt;(batch · full review)"]
        INAPP["In-App Credit Line&lt;br/&gt;(near-real-time · automated)"]
    end

    subgraph Monitoring["📊 Monitoring"]
        DASH["dashboard.py&lt;br/&gt;uptime + avg latency"]
    end

    TXN --&gt; BATCH
    TXN --&gt; STREAM
    BATCH --&gt;|"exact 30d mean"| OFFLINE
    STREAM --&gt;|"EWMA α=0.2"| ONLINE
    OFFLINE --&gt; FAPI
    ONLINE --&gt; FAPI
    FAPI --&gt; UNDER
    FAPI --&gt; INAPP
    FAPI --&gt; DASH

    style BATCH fill:#3b82f6,color:#fff
    style STREAM fill:#f59e0b,color:#fff
    style OFFLINE fill:#10b981,color:#fff
    style ONLINE fill:#ef4444,color:#fff
</pre>
</div>
<p></p></figure><p></p>
</div>
</div>
</div>
<hr>
</section>
<section id="component-architecture" class="level1" data-number="2">
<h1 data-number="2"><span class="header-section-number">2</span> Component Architecture</h1>
<p>The module dependencies and structure of the <code>src/compass</code> repository are organized as follows:</p>
<div class="cell" data-layout-align="default">
<div class="cell-output-display">
<div>
<p></p><figure class="figure"><p></p>
<div>
<pre class="mermaid mermaid-js">graph LR
    subgraph src_compass["src/compass/"]
        CONFIG["config.py&lt;br/&gt;── paths&lt;br/&gt;── NUM_CUSTOMERS=300&lt;br/&gt;── HISTORY_DAYS=180&lt;br/&gt;── TXN_AVG_WINDOW=30d&lt;br/&gt;── EWMA_ALPHA=0.2&lt;br/&gt;── FRESHNESS_TTL=6h"]

        DATAGEN["data_generation.py&lt;br/&gt;── generate_transactions()&lt;br/&gt;── _generate_event_days()&lt;br/&gt;── _amounts_for_day()&lt;br/&gt;Patterns: daily/weekly/sparse"]

        subgraph features_dir["features/"]
            BATCHPIPE["batch_pipeline.py&lt;br/&gt;── run_batch_pipeline()&lt;br/&gt;── compute_txn_amount_avg_30d()&lt;br/&gt;── _load_transactions()"]
            STREAMPIPE["streaming_pipeline.py&lt;br/&gt;── run_streaming_pipeline()&lt;br/&gt;── _load_running_averages()&lt;br/&gt;── _load_ordered_events()&lt;br/&gt;BATCH_SIZE=50"]
        end

        subgraph store_dir["store/"]
            OFFSTORE["offline_store.py&lt;br/&gt;class OfflineStore&lt;br/&gt;── write_features()&lt;br/&gt;── get_features()"]
            ONSTORE["online_store.py&lt;br/&gt;class OnlineStore&lt;br/&gt;── upsert_feature()&lt;br/&gt;── get_features()&lt;br/&gt;── get_all_features()&lt;br/&gt;── get_state()&lt;br/&gt;── set_state()"]
        end

        subgraph serving_dir["serving/"]
            FEATAPI["feature_api.py&lt;br/&gt;── get_offline_features()&lt;br/&gt;── get_online_features()"]
            QUERYCLI["query_cli.py&lt;br/&gt;CLI: query-features"]
        end

        subgraph model_dir["model/"]
            CREDIT["credit_score.py&lt;br/&gt;── score()&lt;br/&gt;── decide()&lt;br/&gt;THRESHOLD=0.5"]
        end

        subgraph monitoring_dir["monitoring/"]
            DASHBOARD["dashboard.py&lt;br/&gt;── run_health_check()&lt;br/&gt;── _sample_customer_ids()&lt;br/&gt;── _time_call()&lt;br/&gt;SAMPLE_SIZE=50"]
        end
    end

    CONFIG --&gt; BATCHPIPE
    CONFIG --&gt; STREAMPIPE
    CONFIG --&gt; DATAGEN
    BATCHPIPE --&gt; OFFSTORE
    STREAMPIPE --&gt; ONSTORE
    OFFSTORE --&gt; FEATAPI
    ONSTORE --&gt; FEATAPI
    FEATAPI --&gt; QUERYCLI
    FEATAPI --&gt; CREDIT
    FEATAPI --&gt; DASHBOARD
</pre>
</div>
<p></p></figure><p></p>
</div>
</div>
</div>
<hr>
</section>
<section id="data-flow-batch-path" class="level1" data-number="3">
<h1 data-number="3"><span class="header-section-number">3</span> Data Flow — Batch Path</h1>
<ul>
<li><strong>Trigger</strong>: Nightly cron / manual <code>uv run batch-pipeline</code></li>
<li><strong>Formula</strong>: <span class="math inline">\(\text{mean}(\text{amount})\)</span> where <span class="math inline">\(\text{event\_timestamp} \in [\text{as\_of} - 30\text{d}, \text{as\_of}]\)</span></li>
</ul>
<div class="cell" data-layout-align="default">
<div class="cell-output-display">
<div>
<p></p><figure class="figure"><p></p>
<div>
<pre class="mermaid mermaid-js">flowchart LR
    A["transactions.csv"] --&gt;|read_csv| B["DataFrame&lt;br/&gt;all 32,929 rows"]
    B --&gt;|"filter: last 30d&lt;br/&gt;from as_of"| C["Windowed DataFrame&lt;br/&gt;per customer"]
    C --&gt;|"groupby customer_id&lt;br/&gt;.mean()"| D["Dict: customer_id to avg"]
    D --&gt;|for each customer| E["OfflineStore\n.write_features()"]
    E --&gt;|INSERT OR REPLACE| F[("offline_store.db\noffline_features\nPK: customer_id, as_of, feature_name")]

    style F fill:#10b981,color:#fff
</pre>
</div>
<p></p></figure><p></p>
</div>
</div>
</div>
<p><strong>Key properties of the batch path:</strong></p>
<ul>
<li><strong>Exact</strong>: Arithmetic mean calculated over a precise time window.</li>
<li><strong>Reproducible</strong>: Same input data always produces the identical feature value.</li>
<li><strong>Point-in-time safe</strong>: Keyed by <code>as_of</code>, preserving historical values for backtesting.</li>
<li>❌ <strong>Expensive</strong>: Requires scanning the full transaction table on every run.</li>
<li>❌ <strong>Latency</strong>: Nightly cadence means features can be up to 24 hours stale at inference.</li>
</ul>
<hr>
</section>
<section id="data-flow-streaming-path" class="level1" data-number="4">
<h1 data-number="4"><span class="header-section-number">4</span> Data Flow — Streaming Path</h1>
<ul>
<li><strong>Trigger</strong>: Continuous event listener / <code>uv run streaming-pipeline</code></li>
<li><strong>Formula</strong>: EWMA — <span class="math inline">\(\alpha \times \text{amount} + (1 - \alpha) \times \text{prev\_avg}\)</span> where <span class="math inline">\(\alpha = 0.2\)</span></li>
</ul>
<div class="cell" data-layout-align="default">
<div class="cell-output-display">
<div>
<p></p><figure class="figure"><p></p>
<div>
<pre class="mermaid mermaid-js">flowchart LR
    A["transactions.csv"] --&gt;|sort by timestamp| B["Ordered Events&lt;br/&gt;with seq index"]
    B --&gt;|"resume from&lt;br/&gt;last_processed_seq"| C["Pending Events&lt;br/&gt;start_seq onwards"]
    C --&gt;|batches of 50| D{"customer_id&lt;br/&gt;in running_avg?"}
    D --&gt;|Yes| E["EWMA Update&lt;br/&gt;0.2 x amount + 0.8 x prev"]
    D --&gt;|No| F["Seed&lt;br/&gt;running_avg = amount"]
    E --&gt; G["OnlineStore&lt;br/&gt;.upsert_feature()"]
    F --&gt; G
    G --&gt;|"UPDATE SET value, computed_at"| H[("online_store.db&lt;br/&gt;online_features&lt;br/&gt;PK: customer_id, feature_name")]
    G --&gt;|UPDATE| I[("pipeline_state&lt;br/&gt;last_processed_seq")]

    style H fill:#ef4444,color:#fff
    style I fill:#fbbf24
</pre>
</div>
<p></p></figure><p></p>
</div>
</div>
</div>
<p><strong>Key properties of the streaming path:</strong></p>
<ul>
<li><strong>Fast</strong>: <span class="math inline">\(O(1)\)</span> computation per event, requiring zero window scans.</li>
<li><strong>Incremental</strong>: Resumes from last processed position using <code>pipeline_state</code>.</li>
<li>❌ <strong>Approximate</strong>: EWMA is an exponential smoother, not a true rolling 30-day window.</li>
<li>❌ <strong>Order-sensitive</strong>: The output is highly dependent on the arrival sequence of transactions.</li>
<li>❌ <strong>Silent staleness</strong>: Does not actively alert or reject queries if ingestion falls behind the <code>FRESHNESS_TTL</code> (6 hours).</li>
</ul>
<hr>
</section>
<section id="database-schema-er-diagram" class="level1" data-number="5">
<h1 data-number="5"><span class="header-section-number">5</span> Database Schema (ER Diagram)</h1>
<p>The structure of the persistent SQLite databases backing the feature store:</p>
<div class="cell" data-layout-align="default">
<div class="cell-output-display">
<div>
<p></p><figure class="figure"><p></p>
<div>
<pre class="mermaid mermaid-js">erDiagram
    OFFLINE_FEATURES {
        TEXT customer_id PK
        TEXT as_of PK
        TEXT feature_name PK
        REAL value
        TEXT computed_at
    }

    ONLINE_FEATURES {
        TEXT customer_id PK
        TEXT feature_name PK
        REAL value
        TEXT computed_at
    }

    PIPELINE_STATE {
        TEXT key PK
        TEXT value
    }

    OFFLINE_FEATURES ||--o{ ONLINE_FEATURES : "same customer_id - no FK"
    ONLINE_FEATURES ||--|| PIPELINE_STATE : "state: last_processed_seq"
</pre>
</div>
<p></p></figure><p></p>
</div>
</div>
</div>
<section id="schema-storage-comparison" class="level2" data-number="5.1">
<h2 data-number="5.1" class="anchored" data-anchor-id="schema-storage-comparison"><span class="header-section-number">5.1</span> Schema &amp; Storage Comparison</h2>
<table class="caption-top table">
<colgroup>
<col style="width: 33%">
<col style="width: 33%">
<col style="width: 33%">
</colgroup>
<thead>
<tr class="header">
<th>Property</th>
<th>Offline Store</th>
<th>Online Store</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><strong>File</strong></td>
<td><code>offline_store.db</code></td>
<td><code>online_store.db</code></td>
</tr>
<tr class="even">
<td><strong>Table</strong></td>
<td><code>offline_features</code></td>
<td><code>online_features</code></td>
</tr>
<tr class="odd">
<td><strong>Primary Key</strong></td>
<td><code>(customer_id, as_of, feature_name)</code></td>
<td><code>(customer_id, feature_name)</code></td>
</tr>
<tr class="even">
<td><strong>History</strong></td>
<td>✅ Retains all point-in-time snapshots</td>
<td>❌ Overwrites with latest value</td>
</tr>
<tr class="odd">
<td><strong>Staleness detection</strong></td>
<td>N/A (point-in-time specific)</td>
<td>❌ Storage-level only; no TTL enforcement</td>
</tr>
<tr class="even">
<td><strong>Feature Formula</strong></td>
<td>Exact 30-day mean</td>
<td>EWMA (<span class="math inline">\(\alpha = 0.2\)</span>)</td>
</tr>
</tbody>
</table>
<hr>
</section>
</section>
<section id="uml-class-module-diagram" class="level1" data-number="6">
<h1 data-number="6"><span class="header-section-number">6</span> UML Class &amp; Module Diagram</h1>
<div class="cell" data-layout-align="default">
<div class="cell-output-display">
<div>
<p></p><figure class="figure"><p></p>
<div>
<pre class="mermaid mermaid-js">classDiagram
    class OfflineStore {
        +db_path: Path
        -_conn: sqlite3.Connection
        +__init__(db_path: Path)
        +write_features(customer_id, as_of, features, computed_at)
        +get_features(customer_id, as_of) dict
        +close()
    }

    class OnlineStore {
        +db_path: Path
        -_conn: sqlite3.Connection
        +__init__(db_path: Path)
        +upsert_feature(customer_id, feature_name, value, computed_at)
        +get_features(customer_id) dict
        +get_all_features() dict
        +get_state(key) str
        +set_state(key, value)
        +close()
    }

    class BatchPipeline {
        +run_batch_pipeline(as_of, store) OfflineStore
        +compute_txn_amount_avg_30d(df, as_of) dict
        -_load_transactions() DataFrame
    }

    class StreamingPipeline {
        +run_streaming_pipeline(store, stop_after_seconds) int
        -_load_ordered_events() DataFrame
        -_load_running_averages(store) dict
        EWMA_ALPHA = 0.2
        _BATCH_SIZE = 50
    }

    class FeatureAPI {
        +get_offline_features(customer_id, as_of) dict
        +get_online_features(customer_id) dict
    }

    class CreditScore {
        +score(features) float
        +decide(features) dict
        DECISION_THRESHOLD = 0.5
        _TXN_AMOUNT_AVG_WEIGHT = -0.01
    }

    class Dashboard {
        +run_health_check() dict
        -_sample_customer_ids(limit) list
        -_time_call(fn, args) tuple
        SAMPLE_SIZE = 50
    }

    BatchPipeline --&gt; OfflineStore : writes to
    StreamingPipeline --&gt; OnlineStore : writes to
    FeatureAPI --&gt; OfflineStore : reads from
    FeatureAPI --&gt; OnlineStore : reads from
    CreditScore ..&gt; FeatureAPI : consumes features
    Dashboard ..&gt; FeatureAPI : probes health
</pre>
</div>
<p></p></figure><p></p>
</div>
</div>
</div>
<hr>
</section>
<section id="execution-sequence-end-to-end" class="level1" data-number="7">
<h1 data-number="7"><span class="header-section-number">7</span> Execution Sequence — End-to-End</h1>
<div class="cell" data-layout-align="default">
<div class="cell-output-display">
<div>
<p></p><figure class="figure"><p></p>
<div>
<pre class="mermaid mermaid-js">sequenceDiagram
    actor User
    participant DG as data_generation
    participant BP as batch_pipeline
    participant SP as streaming_pipeline
    participant OFFSTORE as OfflineStore
    participant ONSTORE as OnlineStore
    participant API as feature_api
    participant CS as credit_score
    participant MON as dashboard

    User-&gt;&gt;DG: "uv run generate-data"
    DG-&gt;&gt;DG: "generate_transactions(300 customers, 180 days)"
    DG--&gt;&gt;User: "transactions.csv (32,929 rows)"

    User-&gt;&gt;BP: "uv run batch-pipeline"
    BP-&gt;&gt;BP: "_load_transactions()"
    BP-&gt;&gt;BP: "compute_txn_amount_avg_30d(df, as_of)"
    Note over BP: EXACT mean over last 30d window
    BP-&gt;&gt;OFFSTORE: "write_features(customer_id, as_of, features)"
    OFFSTORE--&gt;&gt;User: "offline_store.db updated"

    User-&gt;&gt;SP: "uv run streaming-pipeline"
    SP-&gt;&gt;ONSTORE: "get_state('last_processed_seq')"
    ONSTORE--&gt;&gt;SP: "last_seq (resume point)"
    SP-&gt;&gt;SP: "_load_ordered_events()"
    loop For each event batch
        SP-&gt;&gt;SP: "EWMA: 0.2 x amount + 0.8 x prev"
        SP-&gt;&gt;ONSTORE: "upsert_feature(customer_id, feature_name, value)"
        SP-&gt;&gt;ONSTORE: "set_state('last_processed_seq', seq)"
    end
    ONSTORE--&gt;&gt;User: "online_store.db updated"

    User-&gt;&gt;API: "uv run query-features --customer-id C0001"
    API-&gt;&gt;OFFSTORE: "get_features(C0001, as_of=now)"
    OFFSTORE--&gt;&gt;API: "txn_amount_avg_30d = 142.4050"
    API-&gt;&gt;ONSTORE: "get_features(C0001)"
    ONSTORE--&gt;&gt;API: "txn_amount_avg_30d = 76.8235"
    API--&gt;&gt;User: "DIVERGENCE VISIBLE: offline=142.4 vs online=76.8"

    User-&gt;&gt;MON: "uv run monitor"
    MON-&gt;&gt;MON: "_sample_customer_ids(50)"
    MON-&gt;&gt;API: "get_offline_features() x 50 customers"
    MON-&gt;&gt;API: "get_online_features() x 50 customers"
    MON--&gt;&gt;User: "uptime=100%, avg_latency=Xms"
    Note over User,MON: No staleness check! No feature drift alert!
</pre>
</div>
<p></p></figure><p></p>
</div>
</div>
</div>
<hr>
</section>
<section id="the-core-risk-trainingserving-skew" class="level1" data-number="8">
<h1 data-number="8"><span class="header-section-number">8</span> The Core Risk: Training/Serving Skew</h1>
<p>Training/Serving skew is the most significant structural risk identified in Compass. It violates the core assumption of machine learning model stability: <strong>that the serving-time feature distribution matches the training-time feature distribution.</strong></p>
<div class="cell" data-layout-align="default">
<div class="cell-output-display">
<div>
<p></p><figure class="figure"><p></p>
<div>
<pre class="mermaid mermaid-js">graph TB
    subgraph Training["Model Training - Underwriting"]
        T1["Training Data Source:&lt;br/&gt;Offline Store"]
        T2["Feature: txn_amount_avg_30d&lt;br/&gt;= EXACT arithmetic mean&lt;br/&gt;over rolling 30d window"]
        T3["Model learns weights&lt;br/&gt;against EXACT mean values"]
        T1 --&gt; T2 --&gt; T3
    end

    subgraph Serving["Model Serving - In-App Real-Time"]
        S1["Serving Data Source:&lt;br/&gt;Online Store"]
        S2["Feature: txn_amount_avg_30d&lt;br/&gt;= EWMA with alpha=0.2&lt;br/&gt;exponential smoother"]
        S3["Model receives EWMA values&lt;br/&gt;a DIFFERENT distribution!"]
        S1 --&gt; S2 --&gt; S3
    end

    subgraph Impact["Impact"]
        I1["Training/Serving Skew&lt;br/&gt;hidden covariate shift"]
        I2["Model scores are miscalibrated&lt;br/&gt;for real-time decisions"]
        I3["Automatic credit top-ups&lt;br/&gt;approved or denied incorrectly"]
    end

    T3 --&gt;|"SKEW"| I1
    S3 --&gt;|"SKEW"| I1
    I1 --&gt; I2 --&gt; I3

    style I1 fill:#ef4444,color:#fff
    style I2 fill:#f59e0b,color:#fff
    style I3 fill:#dc2626,color:#fff
</pre>
</div>
<p></p></figure><p></p>
</div>
</div>
</div>
<section id="quantifying-the-skew-empirical-validation" class="level2" data-number="8.1">
<h2 data-number="8.1" class="anchored" data-anchor-id="quantifying-the-skew-empirical-validation"><span class="header-section-number">8.1</span> Quantifying the Skew (Empirical Validation)</h2>
<p>Running the query CLI for customer <code>C0001</code> reveals a severe mathematical divergence:</p>
<p><span class="math display">\[\text{Offline (Batch): } 142.41 \quad\text{vs.}\quad \text{Online (Streaming): } 76.82 \quad (\Delta \approx 46\%)\]</span></p>
<section id="mathematical-divergence-exact-mean-vs.-ewma" class="level3" data-number="8.1.1">
<h3 data-number="8.1.1" class="anchored" data-anchor-id="mathematical-divergence-exact-mean-vs.-ewma"><span class="header-section-number">8.1.1</span> Mathematical Divergence: Exact Mean vs.&nbsp;EWMA</h3>
<ul>
<li><strong>Exact Mean (Batch)</strong> treats all transactions within the 30-day window with equal weight (<span class="math inline">\(1/N\)</span>).</li>
<li><strong>EWMA (Online)</strong> discounts older transactions exponentially. Since <span class="math inline">\(\alpha = 0.2\)</span>, the most recent transaction holds <span class="math inline">\(20\%\)</span> of the total weight, while transactions older than a few days contribute almost nothing.</li>
</ul>
<p>This difference creates a <strong>covariate shift</strong> in the features. Downstream models trained on the exact mean will predict incorrectly when evaluated using EWMA inputs.</p>
<hr>
</section>
</section>
</section>
<section id="risk-mapping-business-case-incidents" class="level1" data-number="9">
<h1 data-number="9"><span class="header-section-number">9</span> Risk Mapping &amp; Business Case Incidents</h1>
<section id="incident-analysis" class="level2" data-number="9.1">
<h2 data-number="9.1" class="anchored" data-anchor-id="incident-analysis"><span class="header-section-number">9.1</span> Incident Analysis</h2>
<table class="caption-top table">
<colgroup>
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
</colgroup>
<thead>
<tr class="header">
<th>Incident (from Business Case)</th>
<th>Technical Root Cause</th>
<th>Code Location</th>
<th>Risk Category</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Customer complaint: limit based on “outdated transaction pattern”</td>
<td>Ingestion lagging silently. <code>FRESHNESS_TTL = 6h</code> is defined in config, but <strong>never validated</strong> at read time.</td>
<td><code>online_store.py</code><br><code>config.py</code></td>
<td><strong>Silent Staleness</strong></td>
</tr>
<tr class="even">
<td>Real-time limit adjustments inconsistent with underwriting score</td>
<td>Discrepancy in feature definitions. Training uses exact mean; serving uses EWMA.</td>
<td><code>batch_pipeline.py</code> L28 vs.&nbsp;<code>streaming_pipeline.py</code> L72</td>
<td><strong>Training/Serving Skew</strong></td>
</tr>
<tr class="odd">
<td>Uptime is 100% on dashboard, but credit score quality has degraded</td>
<td>Monitoring is limited to API health (HTTP status, latency). No statistical or data freshness checks exist.</td>
<td><code>monitoring/dashboard.py</code></td>
<td><strong>Blind Monitoring</strong></td>
</tr>
</tbody>
</table>
</section>
<section id="risk-assessment-heat-map" class="level2" data-number="9.2">
<h2 data-number="9.2" class="anchored" data-anchor-id="risk-assessment-heat-map"><span class="header-section-number">9.2</span> Risk Assessment Heat Map</h2>
<table class="caption-top table">
<colgroup>
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
</colgroup>
<thead>
<tr class="header">
<th>Risk</th>
<th>Likelihood</th>
<th>Impact</th>
<th>Priority / Action</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><strong>Training/Serving Skew</strong></td>
<td>High (0.90)</td>
<td>Critical (0.95)</td>
<td>🔴 <strong>Critical</strong> (Fix Immediately)</td>
</tr>
<tr class="even">
<td><strong>No Human Review</strong></td>
<td>Medium-High (0.70)</td>
<td>Critical (0.90)</td>
<td>🔴 <strong>Critical</strong> (Fix Immediately)</td>
</tr>
<tr class="odd">
<td><strong>Silent Staleness</strong></td>
<td>High (0.80)</td>
<td>High (0.85)</td>
<td>🟠 <strong>High</strong> (Fix Before Launch)</td>
</tr>
<tr class="even">
<td><strong>Blind Monitoring</strong></td>
<td>Very High (0.95)</td>
<td>Medium-High (0.70)</td>
<td>🟡 <strong>Medium</strong> (Monitor &amp; Alert)</td>
</tr>
</tbody>
</table>
<hr>
</section>
</section>
<section id="proposed-solution-architecture" class="level1" data-number="10">
<h1 data-number="10"><span class="header-section-number">10</span> Proposed Solution Architecture</h1>
<p>To safely proceed with automated credit-line top-ups, Solara must implement a series of architectural safeguards:</p>
<div class="cell" data-layout-align="default">
<div class="cell-output-display">
<div>
<p></p><figure class="figure"><p></p>
<div>
<pre class="mermaid mermaid-js">graph TB
    subgraph FIX1["Fix 1: Unify Feature Logic"]
        F1A["Extract shared compute_txn_amount_avg_30d()"]
        F1B["Streaming approximates window\nwith a sliding buffer"]
        F1C["OR: document EWMA explicitly\nand train the online model on EWMA features"]
        F1A --&gt; F1B
        F1A --&gt; F1C
    end

    subgraph FIX2["Fix 2: Enforce Freshness TTL"]
        F2A["OnlineStore.get_features() checks computed_at"]
        F2B["If age &gt; FRESHNESS_TTL then raise StaleFeatureError"]
        F2C["feature_api falls back to offline store\nor rejects the request"]
        F2A --&gt; F2B --&gt; F2C
    end

    subgraph FIX3["Fix 3: Monitoring with Drift Detection"]
        F3A["Add feature_drift_monitor()"]
        F3B["Compare online vs offline feature distributions"]
        F3C["Alert if mean delta &gt; threshold (e.g. 15%)"]
        F3D["Track P50/P95 of feature staleness age"]
        F3A --&gt; F3B --&gt; F3C
        F3A --&gt; F3D
    end

    subgraph FIX4["Fix 4: Human Review Gate"]
        F4A["Automated approval only if:&lt;br/&gt;feature_age &lt; 1h&lt;br/&gt;online vs offline delta &lt; 15%&lt;br/&gt;customer has &gt; 30 days history"]
        F4B["Otherwise queue for human review"]
        F4A --&gt; F4B
    end

    FIX1 --&gt; FIX2 --&gt; FIX3 --&gt; FIX4
</pre>
</div>
<p></p></figure><p></p>
</div>
</div>
</div>
<section id="before-vs.-after-controls" class="level2" data-number="10.1">
<h2 data-number="10.1" class="anchored" data-anchor-id="before-vs.-after-controls"><span class="header-section-number">10.1</span> Before vs.&nbsp;After Controls</h2>
<table class="caption-top table">
<colgroup>
<col style="width: 33%">
<col style="width: 33%">
<col style="width: 33%">
</colgroup>
<thead>
<tr class="header">
<th>Control</th>
<th>Before</th>
<th>After</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><strong>Feature Formula</strong></td>
<td>Divergent (Exact Mean vs.&nbsp;EWMA)</td>
<td>Unified (Same arithmetic logic)</td>
</tr>
<tr class="even">
<td><strong>Freshness Validation</strong></td>
<td>❌ None (Stale data served silently)</td>
<td>✅ Read-time verification (Age vs.&nbsp;TTL)</td>
</tr>
<tr class="odd">
<td><strong>Monitoring Dashboard</strong></td>
<td>Latency &amp; uptime only</td>
<td>Uptime, Latency, Staleness P95, Feature Drift</td>
</tr>
<tr class="even">
<td><strong>Top-up Process</strong></td>
<td>Automatic approval with zero fallback</td>
<td>Automated gate with fallback to manual review</td>
</tr>
</tbody>
</table>
<hr>
</section>
</section>
<section id="appendix-execution-commands" class="level1" data-number="11">
<h1 data-number="11"><span class="header-section-number">11</span> Appendix: Execution Commands</h1>
<p>Run the following commands in the workspace root to reproduce these findings:</p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb1"><pre class="sourceCode bash code-with-copy"><code class="sourceCode bash"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="co"># 1. Setup environment and generate raw transaction data</span></span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="ex">uv</span> sync</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="ex">uv</span> run generate-data</span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a><span class="co"># 2. Run both computation pipelines</span></span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a><span class="ex">uv</span> run batch-pipeline</span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a><span class="ex">uv</span> run streaming-pipeline</span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-9"><a href="#cb1-9" aria-hidden="true" tabindex="-1"></a><span class="co"># 3. Query features for a specific customer (verifies the delta)</span></span>
<span id="cb1-10"><a href="#cb1-10" aria-hidden="true" tabindex="-1"></a><span class="ex">uv</span> run query-features <span class="at">--customer-id</span> C0001</span>
<span id="cb1-11"><a href="#cb1-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-12"><a href="#cb1-12" aria-hidden="true" tabindex="-1"></a><span class="co"># 4. Check the serving health dashboard</span></span>
<span id="cb1-13"><a href="#cb1-13" aria-hidden="true" tabindex="-1"></a><span class="ex">uv</span> run monitor</span>
<span id="cb1-14"><a href="#cb1-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-15"><a href="#cb1-15" aria-hidden="true" tabindex="-1"></a><span class="co"># 5. Run the integration test suite</span></span>
<span id="cb1-16"><a href="#cb1-16" aria-hidden="true" tabindex="-1"></a><span class="ex">uv</span> run pytest <span class="at">-v</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    // Ensure there is a toggle, if there isn't float one in the top right
    if (window.document.querySelector('.quarto-color-scheme-toggle') === null) {
      const a = window.document.createElement('a');
      a.classList.add('top-right');
      a.classList.add('quarto-color-scheme-toggle');
      a.href = "";
      a.onclick = function() { try { window.quartoToggleColorScheme(); } catch {} return false; };
      const i = window.document.createElement("i");
      i.classList.add('bi');
      a.appendChild(i);
      window.document.body.appendChild(a);
    }
    setColorSchemeToggle(hasAlternateSentinel())
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->




</body></html>